services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
networks:
  default:
    name: ${GLYGEN_ARRAY_NETWORK:-glygen-array-network}
    external: true
