version: '3.4'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
networks:
  default:
    external:
      name: ${GLYGEN_ARRAY_NETWORK:-glygen-array-network}
